language: android
# sudo set to required because of an issue with how TravisCI handles builds in Docker containers https://github.com/travis-ci/travis-ci/issues/3695.
# Setting sudo to required prevents Travis from testing the project in a Docker container.
sudo: required
jdk: oraclejdk8
dist: trusty

before_cache:
  -rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
  -rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

env:
  global:
    # wait up to 10 minutes for adb to connect to emulator
    - ADB_INSTALL_TIMEOUT=20
    - MALLOC_ARENA_MAX=2
    # git hub token
    - secure: cTVpPLOE3v3nncmqLcG72N6rlnxA6VcDFjDRiV98ZBjLiw2WVuIB68DKqfLYo/3ew4vF5ROvEP+8WY84ZwFZndysny/ikdOZ9oaog00kw5ZivQGC0nxp2oDZFeTDlQ9QN6ewe0y2WGA1NFUu2Xq8r3hEewORQ88vRgS+4kVwf9kNJSe4u1kDR9LoKOZTu4FSlsSCW2VarGRw2pYS1lRfHzoYv2n/OUa9prDAyZQbPvu2bekTbyj3z0RDs8s0NLEl7JfMkDEvjolGZlmaWMS6im5IMPIjnSipr/JtMubvssb8jcU2jK8O2cepZ3xFVUlIzfXUfUa9iz3tEKWWL0OT5sS5Lhtisv+NSuwAOEGhDl0UDMh8C3tyjsXlBUvgTt9QYmNI+oyhY49Di62dWOPF+dRqkSJjx8qqClft+DmgqGPdK49aGBKuwdfO4pXKvNw2jpS6B4OksRewZlr1CkSPlDpd1+Itt0gJMuk+71x7ZKAusDOQpxhDUxsYC0jIDXFcTb3uPYFVIU27lsfex/x/c3LCpdBRjlkjP6+D0W0c3DXfYDInLdr6Xa6WqiWXbuGvQR2lOpBoVshq0n/hDV4X3J32DASDwCd3Nr030+zQuT5+ibKc76KeciwqFzh0oZgpPjKLQDoqVy6FSgC4yW+n8ui/Z4wSEUprv8xWocvV3IQ=

android:
  components:
    # tools required
    - tools
    # The BuildTools version used by your project
    - platform-tools
    - extra-android-m2repository
    - extra-google-android-support

    - build-tools-28.0.3
    # The SDK version used to compile your projects
    - android-28

licenses:
  - 'android-sdk-preview-license-.+'
  - 'android-sdk-license-.+'
  - 'google-gdk-license-.+'

script:
  - echo "Travis branch is $TRAVIS_BRANCH"
  - echo "Travis branch is in pull request $TRAVIS_PULL+REQUEST"
  - chmod 755 gradlew
  - ls -la
  - travis_wait ./gradlew clean --stacktrace
  - travis_wait ./gradlew build --stacktrace
  #Run All tests Unit and Instrumentation
  - travis_wait ./gradlew :android-json-form-wizard:jacocoTestReport --stacktrace
  - travis_wait ./gradlew :android-json-form-wizard:coveralls
  # Generate javadoc
  - travis_wait ./gradlew javadoc

notifications:
  slack:
    secure: fAiZ4yA7DM6nUKh7nqsCTqZBb03VEAvi5NcRu5mNh5coNn/50XNeZl+qpv7Dw70Ef85Y/k68uc6KwTGVqPXEmVq9Hk3e7lqpBNN8rufvgCYDDGPmywBmU5BhSeykKo0Ee7llM3mRR/EipjIWw1+YvMcS3hCoygf/UlMDDhG0Jo0=

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: android-json-form-wizard/build/docs/javadoc/
  on:
    branch: master